['/home/madhekar/work/home-media-app/data/input-data/img/imgIMG_4776.jpeg', '/home/madhekar/work/home-media-app/data/input-data/img/imgIMG_7552.jpeg', '/home/madhekar/work/home-media-app/data/input-data/img/imgIMG_8264.jpeg', '/home/madhekar/work/home-media-app/data/input-data/img/imgIMG_5881.jpeg', '/home/madhekar/work/home-media-app/data/input-data/img/imgIMG_6883.jpeg', '/home/madhekar/work/home-media-app/data/input-data/img/IMG_20210305_184739.jpg', '/home/madhekar/work/home-media-app/data/input-data/img/imgIMG_5376.jpeg', '/home/madhekar/work/home-media-app/data/input-data/img/IMG-20200104-WA0012.jpg', '/home/madhekar/work/home-media-app/data/input-data/img/imgIMG_7836.jpeg', '/home/madhekar/work/home-media-app/data/input-data/img/Coach Eval Sem2 002.png']
RuntimeError: output with shape [1, 224, 224] doesn't match the broadcast shape [3, 224, 224]
Traceback:

File "/home/madhekar/.img-emb/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
File "/home/madhekar/.img-emb/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "/home/madhekar/work/vision/research/code/test/multipage_app/home.py", line 112, in <module>
    pg.run()
File "/home/madhekar/.img-emb/lib/python3.10/site-packages/streamlit/navigation/page.py", line 303, in run
    exec(code, module.__dict__)
File "/home/madhekar/work/vision/research/code/test/multipage_app/pages/metadata_creater.py", line 8, in <module>
    pp.execute()
File "/home/madhekar/work/vision/research/code/test/multipage_app/utils/preprocess_util/preprocess.py", line 136, in execute
    asyncio.run(amain(ilist, metadata_path, metadata_file, number_of_instances, openclip_finetuned))
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
File "/home/madhekar/work/vision/research/code/test/multipage_app/utils/preprocess_util/preprocess.py", line 107, in amain
    res = await co
File "/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
File "/home/madhekar/work/vision/research/code/test/multipage_app/utils/preprocess_util/preprocess.py", line 90, in make_request
    r4 = await awaitUtil.force_awaitable(namesOfPeople)(url, openclip_finetuned)
File "/home/madhekar/work/vision/research/code/test/multipage_app/../awaitUtil.py", line 22, in wrapper
    return f(*args, **kwargs)
File "/home/madhekar/work/vision/research/code/test/multipage_app/utils/preprocess_util/preprocess.py", line 60, in namesOfPeople
    names = entities.getEntityNames(uri, openclip_finetuned)
File "/home/madhekar/work/vision/research/code/test/multipage_app/../entities.py", line 52, in getEntityNames
    transform(Image.open(image)).unsqueeze(0).to(device)
File "/home/madhekar/.img-emb/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
File "/home/madhekar/.img-emb/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
File "/home/madhekar/.img-emb/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
File "/home/madhekar/.img-emb/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 277, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
File "/home/madhekar/.img-emb/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 350, in normalize
    return F_t.normalize(tensor, mean=mean, std=std, inplace=inplace)
File "/home/madhekar/.img-emb/lib/python3.10/site-packages/torchvision/transforms/_functional_tensor.py", line 926, in normalize
    return tensor.sub_(mean).div_(std)
